resource_group_name     = "ghostd0gtfrg"
resource_group_location = "West Europe"
service_plan_name       = "HomesServicePlan"
linux_webapp_name       = "Ghostd0gLinuxWebApp"
source_control_repo_url = "https://github.com/ghostdog87/Homies_Ex2"